"""project_environment

Revision ID: 01bb2ac324d3
Revises: 48bf61de661d
Create Date: 2026-06-08 14:32:36.029848
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "01bb2ac324d3"
down_revision: str | None = "48bf61de661d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_project_slug"), ["slug"], unique=True)

    op.create_table(
        "environment",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("is_preview", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "project_id", name="uq_environment_name_project"),
    )
    with op.batch_alter_table("environment", schema=None) as batch_op:
        batch_op.create_index("ix_environment_name", ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_environment_project_id"), ["project_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("environment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_environment_project_id"))
        batch_op.drop_index("ix_environment_name")

    op.drop_table("environment")
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_slug"))
        batch_op.drop_index(batch_op.f("ix_project_owner_id"))

    op.drop_table("project")
    # ### end Alembic commands ###
