"""registry_credentials

Revision ID: 251a28163a2f
Revises: 32f6b1c7decf
Create Date: 2026-06-09 16:07:00.096208
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "251a28163a2f"
down_revision: str | None = "32f6b1c7decf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shared_registry_credentials",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("username", sa.String(length=1024), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("registry_type", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shared_registry_credentials", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shared_registry_credentials_owner_id"),
            ["owner_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shared_registry_credentials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shared_registry_credentials_owner_id"))

    op.drop_table("shared_registry_credentials")
    # ### end Alembic commands ###
