"""shared_env_variable

Revision ID: 32f6b1c7decf
Revises: 6fc0b7db835e
Create Date: 2026-06-09 13:38:18.111331
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "32f6b1c7decf"
down_revision: str | None = "6fc0b7db835e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shared_env_variable",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("environment_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["environment.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "key", "environment_id", name="uq_shared_env_variable_key_environment"
        ),
    )
    with op.batch_alter_table("shared_env_variable", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shared_env_variable_environment_id"),
            ["environment_id"],
            unique=False,
        )
        batch_op.create_index("ix_shared_env_variable_key", ["key"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shared_env_variable", schema=None) as batch_op:
        batch_op.drop_index("ix_shared_env_variable_key")
        batch_op.drop_index(batch_op.f("ix_shared_env_variable_environment_id"))

    op.drop_table("shared_env_variable")
    # ### end Alembic commands ###
