"""ssh_key

Revision ID: 3f50f074d015
Revises: ffc7e1ba377a
Create Date: 2026-06-10 13:50:59.174881
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "3f50f074d015"
down_revision: str | None = "ffc7e1ba377a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ssh_key",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user", sa.String(length=255), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("private_key", sa.Text(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ssh_key", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ssh_key_slug"), ["slug"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ssh_key", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ssh_key_slug"))

    op.drop_table("ssh_key")
    # ### end Alembic commands ###
