"""compose_stack

Revision ID: 4a8e805e5b72
Revises: 251a28163a2f
Create Date: 2026-06-09 16:56:34.197271
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "4a8e805e5b72"
down_revision: str | None = "251a28163a2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compose_stack",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("slug", sa.String(length=40), nullable=False),
        sa.Column("network_alias_prefix", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("environment_id", sa.String(), nullable=False),
        sa.Column("deploy_token", sa.String(length=35), nullable=True),
        sa.Column("user_content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["environment.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "slug", "environment_id", name="uq_compose_stack_slug_environment"
        ),
    )
    with op.batch_alter_table("compose_stack", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_compose_stack_environment_id"),
            ["environment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_compose_stack_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_compose_stack_slug"), ["slug"], unique=False
        )

    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.add_column(sa.Column("compose_stack_id", sa.String(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_service_compose_stack_id"),
            ["compose_stack_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_service_compose_stack_id",
            "compose_stack",
            ["compose_stack_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.drop_constraint("fk_service_compose_stack_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_service_compose_stack_id"))
        batch_op.drop_column("compose_stack_id")

    with op.batch_alter_table("compose_stack", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_compose_stack_slug"))
        batch_op.drop_index(batch_op.f("ix_compose_stack_project_id"))
        batch_op.drop_index(batch_op.f("ix_compose_stack_environment_id"))

    op.drop_table("compose_stack")
    # ### end Alembic commands ###
