"""service_auto_deploy_enabled

Revision ID: 573648df0d62
Revises: 804605215f39
Create Date: 2026-06-10 11:41:36.032356
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "573648df0d62"
down_revision: str | None = "804605215f39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "auto_deploy_enabled", sa.Boolean(), server_default="1", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.drop_column("auto_deploy_enabled")

    # ### end Alembic commands ###
