"""git_connectors_github_app

Revision ID: 5af5214203f8
Revises: df82bb7586d5
Create Date: 2026-06-10 09:49:05.112803
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "5af5214203f8"
down_revision: str | None = "df82bb7586d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "git_repository",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("repo", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    with op.batch_alter_table("git_repository", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_git_repository_owner"), ["owner"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_git_repository_repo"), ["repo"], unique=False
        )

    op.create_table(
        "github_app",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("installation_id", sa.Integer(), nullable=True),
        sa.Column("app_url", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("client_secret", sa.Text(), nullable=False),
        sa.Column("webhook_secret", sa.Text(), nullable=False),
        sa.Column("private_key", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_id"),
    )
    op.create_table(
        "github_app_repositories",
        sa.Column("github_app_id", sa.String(), nullable=False),
        sa.Column("repository_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["github_app_id"], ["github_app.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["git_repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("github_app_id", "repository_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("github_app_repositories")
    op.drop_table("github_app")
    with op.batch_alter_table("git_repository", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_git_repository_repo"))
        batch_op.drop_index(batch_op.f("ix_git_repository_owner"))

    op.drop_table("git_repository")
    # ### end Alembic commands ###
