"""workspaces

Revision ID: 6db86814170f
Revises: c70955cb65ff
Create Date: 2026-06-10 20:25:11.062854
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "6db86814170f"
down_revision: str | None = "c70955cb65ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workspace", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workspace_slug"), ["slug"], unique=True)

    op.create_table(
        "workspace_membership",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("role", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "workspace_id", name="uq_membership_user_workspace"
        ),
    )
    with op.batch_alter_table("workspace_membership", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workspace_membership_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workspace_membership_workspace_id"),
            ["workspace_id"],
            unique=False,
        )

    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("workspace_id", sa.String(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_project_workspace_id"), ["workspace_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_project_workspace_id",
            "workspace",
            ["workspace_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.drop_constraint("fk_project_workspace_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_project_workspace_id"))
        batch_op.drop_column("workspace_id")

    with op.batch_alter_table("workspace_membership", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workspace_membership_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_workspace_membership_user_id"))

    op.drop_table("workspace_membership")
    with op.batch_alter_table("workspace", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workspace_slug"))

    op.drop_table("workspace")
    # ### end Alembic commands ###
