"""deployment

Revision ID: 6fc0b7db835e
Revises: fa92a00c6738
Create Date: 2026-06-08 16:11:56.247697
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "6fc0b7db835e"
down_revision: str | None = "fa92a00c6738"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deployment",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("slot", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("is_current_production", sa.Boolean(), nullable=False),
        sa.Column("service_id", sa.String(), nullable=False),
        sa.Column("service_snapshot", sa.JSON(), nullable=True),
        sa.Column("commit_message", sa.Text(), nullable=False),
        sa.Column("trigger_method", sa.String(length=15), nullable=False),
        sa.Column("commit_sha", sa.String(length=45), nullable=True),
        sa.Column("commit_author_name", sa.Text(), nullable=True),
        sa.Column("pull_request_number", sa.Integer(), nullable=True),
        sa.Column("ignore_build_cache", sa.Boolean(), nullable=False),
        sa.Column("build_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("build_finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_redeploy_of_id", sa.String(), nullable=True),
        sa.Column(
            "queued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["is_redeploy_of_id"], ["deployment.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deployment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deployment_is_current_production"),
            ["is_current_production"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_deployment_service_id"), ["service_id"], unique=False
        )
        batch_op.create_index("ix_deployment_status", ["status"], unique=False)

    with op.batch_alter_table("deployment_change", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_deployment_change_deployment_id",
            "deployment",
            ["deployment_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deployment_change", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_deployment_change_deployment_id", type_="foreignkey"
        )

    with op.batch_alter_table("deployment", schema=None) as batch_op:
        batch_op.drop_index("ix_deployment_status")
        batch_op.drop_index(batch_op.f("ix_deployment_service_id"))
        batch_op.drop_index(batch_op.f("ix_deployment_is_current_production"))

    op.drop_table("deployment")
    # ### end Alembic commands ###
