"""workspace_invitation

Revision ID: 7437b61c6c79
Revises: 6db86814170f
Create Date: 2026-06-10 20:42:32.442822
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7437b61c6c79'
down_revision: str | None = '6db86814170f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_invitation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'workspace_id', name='uq_invitation_username_workspace')
    )
    with op.batch_alter_table('workspace_invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_invitation_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_workspace_invitation_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_invitation_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_invitation_token'))

    op.drop_table('workspace_invitation')
    # ### end Alembic commands ###
