"""git_app_wrapper

Revision ID: 804605215f39
Revises: 5af5214203f8
Create Date: 2026-06-10 10:09:49.995386
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "804605215f39"
down_revision: str | None = "5af5214203f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "git_app",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("github_app_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["github_app_id"], ["github_app.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_app_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("git_app")
    # ### end Alembic commands ###
