"""preview_env_models

Revision ID: c70955cb65ff
Revises: 3f50f074d015
Create Date: 2026-06-10 17:46:36.512347
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "c70955cb65ff"
down_revision: str | None = "3f50f074d015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preview_env_template",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("base_environment_id", sa.String(), nullable=False),
        sa.Column("auto_teardown", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_environment_id"], ["environment.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("preview_env_template", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_preview_env_template_project_id"),
            ["project_id"],
            unique=False,
        )

    op.create_table(
        "preview_env_metadata",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("environment_id", sa.String(), nullable=False),
        sa.Column("template_id", sa.String(), nullable=True),
        sa.Column("git_app_id", sa.String(), nullable=True),
        sa.Column("pr_number", sa.Integer(), nullable=True),
        sa.Column("branch_name", sa.String(length=255), nullable=False),
        sa.Column("head_repository_url", sa.String(), nullable=False),
        sa.Column("source_trigger", sa.String(length=30), nullable=False),
        sa.Column("deploy_state", sa.String(length=30), nullable=False),
        sa.Column("auto_teardown", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["environment.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["git_app_id"], ["git_app.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["template_id"], ["preview_env_template.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("environment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("preview_env_metadata")
    with op.batch_alter_table("preview_env_template", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_preview_env_template_project_id"))

    op.drop_table("preview_env_template")
    # ### end Alembic commands ###
