"""service_metrics

Revision ID: df82bb7586d5
Revises: 4a8e805e5b72
Create Date: 2026-06-09 20:13:16.652386
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "df82bb7586d5"
down_revision: str | None = "4a8e805e5b72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_metrics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cpu_percent", sa.Float(), nullable=False),
        sa.Column("memory_bytes", sa.BigInteger(), nullable=False),
        sa.Column("net_tx_bytes", sa.BigInteger(), nullable=False),
        sa.Column("net_rx_bytes", sa.BigInteger(), nullable=False),
        sa.Column("disk_read_bytes", sa.BigInteger(), nullable=False),
        sa.Column("disk_writes_bytes", sa.BigInteger(), nullable=False),
        sa.Column("service_id", sa.String(), nullable=False),
        sa.Column("deployment_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployment.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("service_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_service_metrics_deployment_id"),
            ["deployment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_service_metrics_service_id"), ["service_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_service_metrics_service_id"))
        batch_op.drop_index(batch_op.f("ix_service_metrics_deployment_id"))

    op.drop_table("service_metrics")
    # ### end Alembic commands ###
