"""gitlab_app

Revision ID: e333ab623f76
Revises: 573648df0d62
Create Date: 2026-06-10 11:55:31.114468
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "e333ab623f76"
down_revision: str | None = "573648df0d62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gitlab_app",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("gitlab_url", sa.String(), nullable=False),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.Column("app_id", sa.String(length=255), nullable=False),
        sa.Column("secret", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gitlab_app_repositories",
        sa.Column("gitlab_app_id", sa.String(), nullable=False),
        sa.Column("repository_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gitlab_app_id"], ["gitlab_app.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["git_repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("gitlab_app_id", "repository_id"),
    )
    with op.batch_alter_table("git_app", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gitlab_app_id", sa.String(), nullable=True))
        batch_op.create_unique_constraint("uq_git_app_gitlab_app_id", ["gitlab_app_id"])
        batch_op.create_foreign_key(
            "fk_git_app_gitlab_app_id",
            "gitlab_app",
            ["gitlab_app_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("git_app", schema=None) as batch_op:
        batch_op.drop_constraint("fk_git_app_gitlab_app_id", type_="foreignkey")
        batch_op.drop_constraint("uq_git_app_gitlab_app_id", type_="unique")
        batch_op.drop_column("gitlab_app_id")

    op.drop_table("gitlab_app_repositories")
    op.drop_table("gitlab_app")
    # ### end Alembic commands ###
