"""service_config_models

Revision ID: fa92a00c6738
Revises: 01bb2ac324d3
Create Date: 2026-06-08 15:15:05.441214
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "fa92a00c6738"
down_revision: str | None = "01bb2ac324d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("mount_path", sa.String(), nullable=False),
        sa.Column("contents", sa.Text(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_config_mount_path"), ["mount_path"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_config_version"), ["version"], unique=False
        )

    op.create_table(
        "healthcheck",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("associated_port", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "port_configuration",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("host", sa.Integer(), nullable=False),
        sa.Column("forwarded", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("port_configuration", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_port_configuration_host"), ["host"], unique=False
        )

    op.create_table(
        "url",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("base_path", sa.String(), nullable=False),
        sa.Column("strip_prefix", sa.Boolean(), nullable=False),
        sa.Column("redirect_to", sa.JSON(), nullable=True),
        sa.Column("associated_port", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain", "base_path", name="uq_url_domain_base_path"),
    )
    op.create_table(
        "service",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("environment_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("credentials", sa.JSON(), nullable=True),
        sa.Column("command", sa.Text(), nullable=True),
        sa.Column("network_alias", sa.String(), nullable=True),
        sa.Column("resource_limits", sa.JSON(), nullable=True),
        sa.Column("deploy_token", sa.String(), nullable=True),
        sa.Column("healthcheck_id", sa.String(), nullable=True),
        sa.Column("container_registry_credentials_id", sa.String(), nullable=True),
        sa.Column("git_app_id", sa.String(), nullable=True),
        sa.Column("repository_url", sa.String(), nullable=True),
        sa.Column("branch_name", sa.String(), nullable=True),
        sa.Column("commit_sha", sa.String(), nullable=True),
        sa.Column("builder", sa.String(), nullable=True),
        sa.Column("dockerfile_builder_options", sa.JSON(), nullable=True),
        sa.Column("static_dir_builder_options", sa.JSON(), nullable=True),
        sa.Column("nixpacks_builder_options", sa.JSON(), nullable=True),
        sa.Column("railpack_builder_options", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["environment.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["healthcheck_id"], ["healthcheck.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deploy_token"),
        sa.UniqueConstraint(
            "network_alias",
            "project_id",
            "environment_id",
            name="uq_service_network_alias_project_env",
        ),
        sa.UniqueConstraint(
            "slug", "project_id", "environment_id", name="uq_service_slug_project_env"
        ),
    )
    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_service_environment_id"), ["environment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_service_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_service_repository_url"), ["repository_url"], unique=False
        )

    op.create_table(
        "deployment_change",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("field", sa.String(length=20), nullable=False),
        sa.Column("item_id", sa.String(), nullable=True),
        sa.Column("old_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.Column("service_id", sa.String(), nullable=False),
        sa.Column("deployment_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deployment_change", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deployment_change_applied"), ["applied"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deployment_change_field"), ["field"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deployment_change_service_id"), ["service_id"], unique=False
        )

    op.create_table(
        "env_variable",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("service_id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "service_id", name="uq_env_key_service"),
    )
    with op.batch_alter_table("env_variable", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_env_variable_service_id"), ["service_id"], unique=False
        )

    op.create_table(
        "service_configs",
        sa.Column("service_id", sa.String(), nullable=False),
        sa.Column("config_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["config_id"], ["config.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("service_id", "config_id"),
    )
    op.create_table(
        "service_ports",
        sa.Column("service_id", sa.String(), nullable=False),
        sa.Column("port_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["port_id"], ["port_configuration.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("service_id", "port_id"),
    )
    op.create_table(
        "service_urls",
        sa.Column("service_id", sa.String(), nullable=False),
        sa.Column("url_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["url_id"], ["url.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("service_id", "url_id"),
    )
    op.create_table(
        "volume",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("container_path", sa.String(), nullable=False),
        sa.Column("host_path", sa.String(), nullable=True),
        sa.Column("service_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("volume", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_volume_container_path"), ["container_path"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_volume_host_path"), ["host_path"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_volume_service_id"), ["service_id"], unique=False
        )

    op.create_table(
        "shared_volume",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("volume_id", sa.String(), nullable=False),
        sa.Column("reader_id", sa.String(), nullable=False),
        sa.Column("container_path", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["reader_id"], ["service.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["volume_id"], ["volume.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("volume_id", "reader_id", name="uq_shared_volume_reader"),
    )
    with op.batch_alter_table("shared_volume", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shared_volume_container_path"),
            ["container_path"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shared_volume", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shared_volume_container_path"))

    op.drop_table("shared_volume")
    with op.batch_alter_table("volume", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_volume_service_id"))
        batch_op.drop_index(batch_op.f("ix_volume_host_path"))
        batch_op.drop_index(batch_op.f("ix_volume_container_path"))

    op.drop_table("volume")
    op.drop_table("service_urls")
    op.drop_table("service_ports")
    op.drop_table("service_configs")
    with op.batch_alter_table("env_variable", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_env_variable_service_id"))

    op.drop_table("env_variable")
    with op.batch_alter_table("deployment_change", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deployment_change_service_id"))
        batch_op.drop_index(batch_op.f("ix_deployment_change_field"))
        batch_op.drop_index(batch_op.f("ix_deployment_change_applied"))

    op.drop_table("deployment_change")
    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_service_repository_url"))
        batch_op.drop_index(batch_op.f("ix_service_project_id"))
        batch_op.drop_index(batch_op.f("ix_service_environment_id"))

    op.drop_table("service")
    op.drop_table("url")
    with op.batch_alter_table("port_configuration", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_port_configuration_host"))

    op.drop_table("port_configuration")
    op.drop_table("healthcheck")
    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_config_version"))
        batch_op.drop_index(batch_op.f("ix_config_mount_path"))

    op.drop_table("config")
    # ### end Alembic commands ###
