"""gitlab_webhook_secret

Revision ID: ffc7e1ba377a
Revises: e333ab623f76
Create Date: 2026-06-10 13:14:26.620877
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "ffc7e1ba377a"
down_revision: str | None = "e333ab623f76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gitlab_app", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("webhook_secret", sa.String(length=65), nullable=False)
        )
        batch_op.create_unique_constraint(
            "uq_gitlab_app_webhook_secret", ["webhook_secret"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gitlab_app", schema=None) as batch_op:
        batch_op.drop_constraint("uq_gitlab_app_webhook_secret", type_="unique")
        batch_op.drop_column("webhook_secret")

    # ### end Alembic commands ###
