/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/ping": {
    /** Ping */
    get: operations["ping_api_ping_get"];
  };
  "/api/auth/login": {
    /** Login View */
    post: operations["login_view_api_auth_login_post"];
  };
  "/api/auth/logout": {
    /** Logout View */
    delete: operations["logout_view_api_auth_logout_delete"];
  };
  "/api/auth/me": {
    /** Me View */
    get: operations["me_view_api_auth_me_get"];
  };
  "/api/csrf": {
    /** Csrf View */
    get: operations["csrf_view_api_csrf_get"];
  };
  "/api/auth/check-user-existence": {
    /** Check User Existence */
    get: operations["check_user_existence_api_auth_check_user_existence_get"];
  };
  "/api/auth/create-initial-user": {
    /** Create Initial User */
    post: operations["create_initial_user_api_auth_create_initial_user_post"];
  };
  "/api/auth/change-password": {
    /** Change Password */
    post: operations["change_password_api_auth_change_password_post"];
  };
  "/api/auth/update-profile": {
    /** Update Profile */
    patch: operations["update_profile_api_auth_update_profile_patch"];
  };
  "/api/settings": {
    /** Get Api Settings */
    get: operations["get_api_settings_api_settings_get"];
  };
  "/api/server/resource-limits": {
    /** Get Server Resource Limits View */
    get: operations["get_server_resource_limits_view_api_server_resource_limits_get"];
  };
  "/api/projects/": {
    /** List Projects */
    get: operations["list_projects_api_projects__get"];
    /** Create Project */
    post: operations["create_project_api_projects__post"];
  };
  "/api/projects/{slug}/": {
    /** Get Project */
    get: operations["get_project_api_projects__slug___get"];
    /** Update Project */
    put: operations["update_project_api_projects__slug___put"];
  };
  "/api/docker/image-search/": {
    /** Image Search */
    get: operations["image_search_api_docker_image_search__get"];
  };
  "/api/projects/{project_slug}/{env_slug}/create-service/docker/": {
    /** Create Docker Service */
    post: operations["create_docker_service_api_projects__project_slug___env_slug__create_service_docker__post"];
  };
  "/api/projects/{project_slug}/{env_slug}/service-list/": {
    /** Service List */
    get: operations["service_list_api_projects__project_slug___env_slug__service_list__get"];
  };
  "/api/projects/{project_slug}/{env_slug}/service-details/{slug}/": {
    /** Get Service */
    get: operations["get_service_api_projects__project_slug___env_slug__service_details__slug___get"];
    /** Update Service */
    patch: operations["update_service_api_projects__project_slug___env_slug__service_details__slug___patch"];
  };
  "/api/projects/{project_slug}/{env_slug}/deploy-service/docker/{slug}/": {
    /** Deploy Docker Service View */
    put: operations["deploy_docker_service_view_api_projects__project_slug___env_slug__deploy_service_docker__slug___put"];
  };
  "/api/projects/{project_slug}/{env_slug}/request-service-changes/{slug}/": {
    /** Request Service Changes */
    put: operations["request_service_changes_api_projects__project_slug___env_slug__request_service_changes__slug___put"];
  };
  "/api/projects/{project_slug}/{env_slug}/cancel-service-changes/{slug}/{change_id}/": {
    /** Cancel Service Changes */
    delete: operations["cancel_service_changes_api_projects__project_slug___env_slug__cancel_service_changes__slug___change_id___delete"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AuthedResponse */
    AuthedResponse: {
      user: components["schemas"]["UserSchema"];
      /** Membership */
      membership?: null;
    };
    /** CSRFResponse */
    CSRFResponse: {
      /** Details */
      details: string;
    };
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
      /** Confirm Password */
      confirm_password: string;
    };
    /** ChangePasswordResponse */
    ChangePasswordResponse: {
      /** Success */
      success: boolean;
    };
    /** ChangeSchema */
    ChangeSchema: {
      /** Id */
      id: string;
      /** Type */
      type: string;
      /** Field */
      field: string;
      /** Item Id */
      item_id: string | null;
      /** Old Value */
      old_value: unknown;
      /** New Value */
      new_value: unknown;
      /** Applied */
      applied: boolean;
    };
    /** ConfigSchema */
    ConfigSchema: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Mount Path */
      mount_path: string;
      /** Contents */
      contents: string;
      /** Language */
      language: string;
      /** Version */
      version: number;
    };
    /** DeploymentSchema */
    DeploymentSchema: {
      /** Id */
      id: string;
      /** Status */
      status: string;
      /** Status Reason */
      status_reason: string | null;
      /** Slot */
      slot: string;
      /** Is Current Production */
      is_current_production: boolean;
      /** Commit Message */
      commit_message: string;
      /**
       * Queued At
       * Format: date-time
       */
      queued_at: string;
      /** Started At */
      started_at: string | null;
      /** Finished At */
      finished_at: string | null;
    };
    /** DockerImageResult */
    DockerImageResult: {
      /** Full Image */
      full_image: string;
      /** Description */
      description: string;
    };
    /** DockerImageSearchResponse */
    DockerImageSearchResponse: {
      /** Images */
      images: components["schemas"]["DockerImageResult"][];
    };
    /** DockerServiceCreateRequest */
    DockerServiceCreateRequest: {
      /** Slug */
      slug?: string | null;
      /** Image */
      image: string;
      /** Container Registry Credentials Id */
      container_registry_credentials_id?: string | null;
    };
    /** EnvVariableSchema */
    EnvVariableSchema: {
      /** Id */
      id: string;
      /** Key */
      key: string;
      /** Value */
      value: string;
    };
    /** HealthCheckSchema */
    HealthCheckSchema: {
      /** Id */
      id: string;
      /** Type */
      type: string;
      /** Value */
      value: string;
      /** Interval Seconds */
      interval_seconds: number;
      /** Timeout Seconds */
      timeout_seconds: number;
      /** Associated Port */
      associated_port: number | null;
    };
    /** LoginRequest */
    LoginRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** LoginSuccessResponse */
    LoginSuccessResponse: {
      /** Success */
      success: boolean;
    };
    /** PingResponse */
    PingResponse: {
      /**
       * Ping
       * @default pong
       * @constant
       */
      ping?: "pong";
    };
    /** PortSchema */
    PortSchema: {
      /** Id */
      id: string;
      /** Host */
      host: number;
      /** Forwarded */
      forwarded: number;
    };
    /** ProjectCreateRequest */
    ProjectCreateRequest: {
      /** Slug */
      slug?: string | null;
      /** Description */
      description?: string | null;
    };
    /** ProjectSchema */
    ProjectSchema: {
      /** Id */
      id: string;
      /** Slug */
      slug: string;
      /** Description */
      description: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Environments */
      environments: components["schemas"]["SimpleEnvironmentSchema"][];
      /**
       * Healthy Services
       * @default 0
       */
      healthy_services?: number;
      /**
       * Total Services
       * @default 0
       */
      total_services?: number;
      /**
       * Healthy Stack Services
       * @default 0
       */
      healthy_stack_services?: number;
      /**
       * Total Stack Services
       * @default 0
       */
      total_stack_services?: number;
    };
    /** ProjectUpdateRequest */
    ProjectUpdateRequest: {
      /** Slug */
      slug?: string | null;
      /** Description */
      description?: string | null;
    };
    /** ResourceLimitResponse */
    ResourceLimitResponse: {
      /** No Of Cpus */
      no_of_cpus: number;
      /** Max Memory In Bytes */
      max_memory_in_bytes: number;
    };
    /** ServiceCardSchema */
    ServiceCardSchema: {
      /** Id */
      id: string;
      /** Slug */
      slug: string;
      /** Type */
      type: string;
      /** Status */
      status: string;
      /** Image */
      image: string | null;
      /** Tag */
      tag: string | null;
      /** Url */
      url: string | null;
      /** Volume Number */
      volume_number: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ServiceChangeRequest */
    ServiceChangeRequest: {
      /** Field */
      field: string;
      /** Type */
      type: string;
      /** Item Id */
      item_id?: string | null;
      /** New Value */
      new_value?: unknown;
    };
    /** ServiceSchema */
    ServiceSchema: {
      /** Id */
      id: string;
      /** Slug */
      slug: string;
      /** Type */
      type: string;
      /** Image */
      image: string | null;
      /** Command */
      command: string | null;
      /** Network Alias */
      network_alias: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Urls */
      urls: components["schemas"]["URLSchema"][];
      /** Ports */
      ports: components["schemas"]["PortSchema"][];
      /** Volumes */
      volumes: components["schemas"]["VolumeSchema"][];
      /** Env Variables */
      env_variables: components["schemas"]["EnvVariableSchema"][];
      /** Configs */
      configs: components["schemas"]["ConfigSchema"][];
      healthcheck: components["schemas"]["HealthCheckSchema"] | null;
      /** Unapplied Changes */
      unapplied_changes: components["schemas"]["ChangeSchema"][];
    };
    /** ServiceUpdateRequest */
    ServiceUpdateRequest: {
      /** Slug */
      slug: string;
    };
    /** SettingsResponse */
    SettingsResponse: {
      /** Root Domain */
      root_domain: string;
      /** App Domain */
      app_domain: string;
      /** Image Version */
      image_version: string;
      /** Commit Sha */
      commit_sha: string | null;
    };
    /** SimpleEnvironmentSchema */
    SimpleEnvironmentSchema: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Is Preview */
      is_preview: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** URLSchema */
    URLSchema: {
      /** Id */
      id: string;
      /** Domain */
      domain: string;
      /** Base Path */
      base_path: string;
      /** Strip Prefix */
      strip_prefix: boolean;
      /** Redirect To */
      redirect_to: {
        [key: string]: unknown;
      } | null;
      /** Associated Port */
      associated_port: number | null;
    };
    /** UpdateProfileRequest */
    UpdateProfileRequest: {
      /** Username */
      username?: string | null;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
    };
    /** UserCreatedResponse */
    UserCreatedResponse: {
      /** Detail */
      detail: string;
    };
    /** UserCreationRequest */
    UserCreationRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** UserExistenceResponse */
    UserExistenceResponse: {
      /** Exists */
      exists: boolean;
    };
    /** UserSchema */
    UserSchema: {
      /** Username */
      username: string;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
      /** Is Superuser */
      is_superuser: boolean;
    };
    /** VolumeSchema */
    VolumeSchema: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Mode */
      mode: string;
      /** Container Path */
      container_path: string;
      /** Host Path */
      host_path: string | null;
    };
    ValidationErrorItem: {
      code: string;
      detail: string;
      attr: string;
    };
    ClientServerErrorItem: {
      code: string;
      detail: string;
      attr: string | null;
    };
    ValidationErrorResponse: {
      /** @enum {string} */
      type: "validation_error";
      errors: components["schemas"]["ValidationErrorItem"][];
    };
    ClientErrorResponse: {
      /** @enum {string} */
      type: "client_error";
      errors: components["schemas"]["ClientServerErrorItem"][];
    };
    ServerErrorResponse: {
      /** @enum {string} */
      type: "server_error";
      errors: components["schemas"]["ClientServerErrorItem"][];
    };
    ErrorResponse: components["schemas"]["ValidationErrorResponse"] | components["schemas"]["ClientErrorResponse"] | components["schemas"]["ServerErrorResponse"];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Ping */
  ping_api_ping_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PingResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Login View */
  login_view_api_auth_login_post: {
    parameters: {
      query?: {
        redirect_to?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["LoginSuccessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Logout View */
  logout_view_api_auth_logout_delete: {
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Me View */
  me_view_api_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AuthedResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Csrf View */
  csrf_view_api_csrf_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CSRFResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Check User Existence */
  check_user_existence_api_auth_check_user_existence_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserExistenceResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Create Initial User */
  create_initial_user_api_auth_create_initial_user_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["UserCreatedResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Change Password */
  change_password_api_auth_change_password_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ChangePasswordResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Update Profile */
  update_profile_api_auth_update_profile_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get Api Settings */
  get_api_settings_api_settings_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get Server Resource Limits View */
  get_server_resource_limits_view_api_server_resource_limits_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ResourceLimitResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** List Projects */
  list_projects_api_projects__get: {
    parameters: {
      query?: {
        slug?: string | null;
        sort_by?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectSchema"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Create Project */
  create_project_api_projects__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ProjectSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get Project */
  get_project_api_projects__slug___get: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Update Project */
  update_project_api_projects__slug___put: {
    parameters: {
      path: {
        slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Image Search */
  image_search_api_docker_image_search__get: {
    parameters: {
      query?: {
        q?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DockerImageSearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Create Docker Service */
  create_docker_service_api_projects__project_slug___env_slug__create_service_docker__post: {
    parameters: {
      path: {
        project_slug: string;
        env_slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DockerServiceCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ServiceSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Service List */
  service_list_api_projects__project_slug___env_slug__service_list__get: {
    parameters: {
      query?: {
        query?: string | null;
      };
      path: {
        project_slug: string;
        env_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ServiceCardSchema"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get Service */
  get_service_api_projects__project_slug___env_slug__service_details__slug___get: {
    parameters: {
      path: {
        project_slug: string;
        env_slug: string;
        slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ServiceSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Update Service */
  update_service_api_projects__project_slug___env_slug__service_details__slug___patch: {
    parameters: {
      path: {
        project_slug: string;
        env_slug: string;
        slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ServiceUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ServiceSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Deploy Docker Service View */
  deploy_docker_service_view_api_projects__project_slug___env_slug__deploy_service_docker__slug___put: {
    parameters: {
      path: {
        project_slug: string;
        env_slug: string;
        slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DeploymentSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Request Service Changes */
  request_service_changes_api_projects__project_slug___env_slug__request_service_changes__slug___put: {
    parameters: {
      path: {
        project_slug: string;
        env_slug: string;
        slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ServiceChangeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ServiceSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Cancel Service Changes */
  cancel_service_changes_api_projects__project_slug___env_slug__cancel_service_changes__slug___change_id___delete: {
    parameters: {
      path: {
        project_slug: string;
        env_slug: string;
        slug: string;
        change_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
