/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/ping": {
    /** Ping */
    get: operations["ping_api_ping_get"];
  };
  "/api/auth/login": {
    /** Login View */
    post: operations["login_view_api_auth_login_post"];
  };
  "/api/auth/logout": {
    /** Logout View */
    delete: operations["logout_view_api_auth_logout_delete"];
  };
  "/api/auth/me": {
    /** Me View */
    get: operations["me_view_api_auth_me_get"];
  };
  "/api/csrf": {
    /** Csrf View */
    get: operations["csrf_view_api_csrf_get"];
  };
  "/api/auth/check-user-existence": {
    /** Check User Existence */
    get: operations["check_user_existence_api_auth_check_user_existence_get"];
  };
  "/api/auth/create-initial-user": {
    /** Create Initial User */
    post: operations["create_initial_user_api_auth_create_initial_user_post"];
  };
  "/api/auth/change-password": {
    /** Change Password */
    post: operations["change_password_api_auth_change_password_post"];
  };
  "/api/auth/update-profile": {
    /** Update Profile */
    patch: operations["update_profile_api_auth_update_profile_patch"];
  };
  "/api/settings": {
    /** Get Api Settings */
    get: operations["get_api_settings_api_settings_get"];
  };
  "/api/server/resource-limits": {
    /** Get Server Resource Limits View */
    get: operations["get_server_resource_limits_view_api_server_resource_limits_get"];
  };
  "/api/projects/": {
    /** List Projects */
    get: operations["list_projects_api_projects__get"];
    /** Create Project */
    post: operations["create_project_api_projects__post"];
  };
  "/api/projects/{slug}/": {
    /** Get Project */
    get: operations["get_project_api_projects__slug___get"];
    /** Update Project */
    put: operations["update_project_api_projects__slug___put"];
  };
  "/api/docker/image-search/": {
    /** Image Search */
    get: operations["image_search_api_docker_image_search__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AuthedResponse */
    AuthedResponse: {
      user: components["schemas"]["UserSchema"];
      /** Membership */
      membership?: null;
    };
    /** CSRFResponse */
    CSRFResponse: {
      /** Details */
      details: string;
    };
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
      /** Confirm Password */
      confirm_password: string;
    };
    /** ChangePasswordResponse */
    ChangePasswordResponse: {
      /** Success */
      success: boolean;
    };
    /** DockerImageResult */
    DockerImageResult: {
      /** Full Image */
      full_image: string;
      /** Description */
      description: string;
    };
    /** DockerImageSearchResponse */
    DockerImageSearchResponse: {
      /** Images */
      images: components["schemas"]["DockerImageResult"][];
    };
    /** LoginRequest */
    LoginRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** LoginSuccessResponse */
    LoginSuccessResponse: {
      /** Success */
      success: boolean;
    };
    /** PingResponse */
    PingResponse: {
      /**
       * Ping
       * @default pong
       * @constant
       */
      ping?: "pong";
    };
    /** ProjectCreateRequest */
    ProjectCreateRequest: {
      /** Slug */
      slug?: string | null;
      /** Description */
      description?: string | null;
    };
    /** ProjectSchema */
    ProjectSchema: {
      /** Id */
      id: string;
      /** Slug */
      slug: string;
      /** Description */
      description: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Environments */
      environments: components["schemas"]["SimpleEnvironmentSchema"][];
      /**
       * Healthy Services
       * @default 0
       */
      healthy_services?: number;
      /**
       * Total Services
       * @default 0
       */
      total_services?: number;
      /**
       * Healthy Stack Services
       * @default 0
       */
      healthy_stack_services?: number;
      /**
       * Total Stack Services
       * @default 0
       */
      total_stack_services?: number;
    };
    /** ProjectUpdateRequest */
    ProjectUpdateRequest: {
      /** Slug */
      slug?: string | null;
      /** Description */
      description?: string | null;
    };
    /** ResourceLimitResponse */
    ResourceLimitResponse: {
      /** No Of Cpus */
      no_of_cpus: number;
      /** Max Memory In Bytes */
      max_memory_in_bytes: number;
    };
    /** SettingsResponse */
    SettingsResponse: {
      /** Root Domain */
      root_domain: string;
      /** App Domain */
      app_domain: string;
      /** Image Version */
      image_version: string;
      /** Commit Sha */
      commit_sha: string | null;
    };
    /** SimpleEnvironmentSchema */
    SimpleEnvironmentSchema: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Is Preview */
      is_preview: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** UpdateProfileRequest */
    UpdateProfileRequest: {
      /** Username */
      username?: string | null;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
    };
    /** UserCreatedResponse */
    UserCreatedResponse: {
      /** Detail */
      detail: string;
    };
    /** UserCreationRequest */
    UserCreationRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** UserExistenceResponse */
    UserExistenceResponse: {
      /** Exists */
      exists: boolean;
    };
    /** UserSchema */
    UserSchema: {
      /** Username */
      username: string;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
      /** Is Superuser */
      is_superuser: boolean;
    };
    ValidationErrorItem: {
      code: string;
      detail: string;
      attr: string;
    };
    ClientServerErrorItem: {
      code: string;
      detail: string;
      attr: string | null;
    };
    ValidationErrorResponse: {
      /** @enum {string} */
      type: "validation_error";
      errors: components["schemas"]["ValidationErrorItem"][];
    };
    ClientErrorResponse: {
      /** @enum {string} */
      type: "client_error";
      errors: components["schemas"]["ClientServerErrorItem"][];
    };
    ServerErrorResponse: {
      /** @enum {string} */
      type: "server_error";
      errors: components["schemas"]["ClientServerErrorItem"][];
    };
    ErrorResponse: components["schemas"]["ValidationErrorResponse"] | components["schemas"]["ClientErrorResponse"] | components["schemas"]["ServerErrorResponse"];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Ping */
  ping_api_ping_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PingResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Login View */
  login_view_api_auth_login_post: {
    parameters: {
      query?: {
        redirect_to?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["LoginSuccessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Logout View */
  logout_view_api_auth_logout_delete: {
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Me View */
  me_view_api_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AuthedResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Csrf View */
  csrf_view_api_csrf_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CSRFResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Check User Existence */
  check_user_existence_api_auth_check_user_existence_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserExistenceResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Create Initial User */
  create_initial_user_api_auth_create_initial_user_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["UserCreatedResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Change Password */
  change_password_api_auth_change_password_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ChangePasswordResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Update Profile */
  update_profile_api_auth_update_profile_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get Api Settings */
  get_api_settings_api_settings_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get Server Resource Limits View */
  get_server_resource_limits_view_api_server_resource_limits_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ResourceLimitResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** List Projects */
  list_projects_api_projects__get: {
    parameters: {
      query?: {
        slug?: string | null;
        sort_by?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectSchema"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Create Project */
  create_project_api_projects__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ProjectSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get Project */
  get_project_api_projects__slug___get: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Update Project */
  update_project_api_projects__slug___put: {
    parameters: {
      path: {
        slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Image Search */
  image_search_api_docker_image_search__get: {
    parameters: {
      query?: {
        q?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DockerImageSearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
